# Generated by Django 3.2.4 on 2022-01-04 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('OnlineExamination', '0002_auto_20220104_2348'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='height_field',
        ),
        migrations.RemoveField(
            model_name='student',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='student',
            name='width_field',
        ),
    ]
